### PR TITLE
Make owoify not break commands

### PR DESCRIPTION
**Pull request by banoargeek**
It has come to my attention that apparently owoify breaks things like "!pvp" and the like, so it was proposed that I should just include "HOOK_LOW" for the hook's arguments. This is what the PR accomplishes.

### CODE REVIEW

**Comment by banoargeek** [comment]
Looks as though I made a mistake, this does not work on the dev server.

**Review by plally — COMMENTED** [review]
looks fine except for the fact the diff has your .idea folder in it

**Comment by banoargeek** [comment]
Besides removing .idea, I'm going to take another stab at this project later. I have no idea what to fix besides refactoring the whole thing and studying ULX's chat.lua to do so.

**Comment by banoargeek** [comment]
This PR may be useless, probably the dev server being dumb

**Comment by banoargeek** [comment]
Alright, so I did some discussing with @legokidlogan and @wrefgtzweve. What is strange is that in Solo with GCompute, it seems as though owoify does *not* affect commands in a way that prevents them from working. However, when on the master branch (which does not have HOOK_LOW on my hook might I add) on Dev & CFC3 @legokidlogan claims that no chat commands work at all. I'd like to see if adding HOOK_LOW to the hook will solve the problem, but without Phatso's assistance I'd need to wait for this to be merged to find out.

**Comment by banoargeek** [comment]
> 
> 
> Alright, so I did some discussing with @legokidlogan and @wrefgtzweve. What is strange is that in Solo with GCompute, it seems as though owoify does _not_ affect commands in a way that prevents them from working. However, when on the master branch (which does not have HOOK_LOW on my hook might I add) on Dev & CFC3 @legokidlogan claims that no chat commands work at all. I'd like to see if adding HOOK_LOW to the hook will solve the problem, but without Phatso's assistance I'd need to wait for this to be merged to find out.

Okay apparently after doing some testing @wrefgtzweve has confirmed it is working on the dev server, which is odd because Master does not have HOOK_LOW... I don't know why it's broken on CFC3 hmm...

**Pull request closed without merging**
